name: Ubuntu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Install test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install
        run: ./install.sh

